name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  HAXE_VERSION: 4.2.5
  PROJECT_NAME: AnderEngine

jobs:
  android:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: HaxeFoundation/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache haxelib
        uses: actions/cache@v4
        with:
          path: ~/haxelib
          key: haxelib-${{ runner.os }}-${{ hashFiles('**/hmm.json') }}
          restore-keys: haxelib-${{ runner.os }}

      - name: Install libs
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Build APK ARM64
        run: haxelib run lime build android -release -DONLY_ARM64

      - name: Build AAB
        run: haxelib run lime build android -release -DONLY_ARM64 -Daab

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-APK
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-AAB
          path: export/release/android/bin/app/build/outputs/bundle/release/*.aab