name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

env:
  HAXE_VERSION: 4.2.5
  PROJECT_NAME: AnderEngine

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # HAXE MODERNO
      - name: Setup Haxe
        uses: HaxeFoundation/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      # Dependência Linux (vídeo)
      - name: Install libVLC
        if: inputs.name == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libvlc-dev libvlccore-dev

      # Instalar libs Haxe
      - name: Install Libraries
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      # CONFIGURAÇÃO ANDROID REAL DO RUNNER
      - name: Configure Android
        if: inputs.name == 'Android'
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
          echo "JAVA_HOME=$JAVA_HOME"

          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      # COMPILAR
      - name: Compile
        run: haxelib run lime build ${{ inputs.buildArgs }}

      # GERAR IPA (iOS)
      - name: Make IPA
        if: inputs.name == 'iOS'
        run: |
          cd export/release/ios/build/Release-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r ${{ env.PROJECT_NAME }}.ipa Payload

      # UPLOAD DO BUILD
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          if-no-files-found: error