name: Main
on: workflow_dispatch

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64
            os: windows-latest
            buildArgs: windows
            artifactName: Windows x64
            artifactPath: export/release/windows/bin/*

          - name: Windows x32
            os: windows-latest
            buildArgs: "windows -32 -D HXCPP_M32 -D 32bits"
            artifactName: Windows x32
            artifactPath: export/32bit/windows/bin/*

          - name: Linux
            os: ubuntu-latest
            buildArgs: linux
            artifactName: Linux
            artifactPath: export/release/linux/bin/*

          - name: MacOS
            os: macos-latest
            buildArgs: mac
            artifactName: MacOS
            artifactPath: export/release/macos/bin/*

          - name: Android
            os: macos-latest
            buildArgs: "android -ONLY_ARM64"
            artifactName: Android
            artifactPath: export/release/android/bin/app/build/outputs/apk/release/*.apk

          - name: iOS
            os: macos-latest
            buildArgs: "ios -nosign"
            artifactName: IOS
            artifactPath: export/release/ios/build/Release-iphoneos/*.ipa

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}